- name: Create secrets abd test it
  hosts: localhost
  tasks:
#    - name: Create file with vault creds secrets
#      ansible.builtin.lineinfile:
#        path: ~/secrets.json
#        line: "{{ lookup('hashi_vault', 'secret=common/data/common token={{ vault_token }} url=https://vault-internal.dkdevops.online:8200 validate_certs=False')}}"
#        create: yes
      - name: Debug vault token
        debug:
          msg: "{{ vault_token }}"


