- name: Create secrets abd test it
  hosts: localhost
  become: true
  tasks:
    - name: Create file with vault creds secrets
      ansible.builtin.lineinfile:
        path: ~/secrets.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/common token={{ vault_token }} url=https://vault-internal.dkdevops.online:8200 validate_certs=False')}}"
        create: yes

    - name: Print the secrets
      ansible.builtin.shell: cat ~/secrets.json

    - name: Print the token using ansible
      ansible.builtin.debug:
        msg: "{{ vault_token }}"