format_version: 10
pipelines:
  secrets:
    group: test
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/learn-ansible.git
        shallow_clone: false
        branch: main
    secure_variables:
      vault_token: AES:N5JXJVhIJm9y2HkjtQm41w==:aGpaK62yFUdVnCjl7sFPepVyPAL29mSTMXFQdY/tBnk=
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            secrets_retrieval:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - secrets.yml
                      - -e
                      - vault_token={{ vault_token }}
                    command: ansible-playbook
                    run_if: passed


