format_version: 10
pipelines:
  secrets:
    group: test
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/learn-ansible.git
        shallow_clone: false
        branch: main
    environment_variables:
      vault: hi
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            secrets_retrieval:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - secrets.yml
                      - -e
                      - vault_token={{vault}}
                    command: ansible-playbook secrets.yml -e vault_token=$vault
                    run_if: passed


